### PR TITLE
Add arm64 binary and script to update sha256sum

### PR DESCRIPTION
**Pull request by qubist-pixel-ux**

### CODE REVIEW

**Comment by dae** [comment]
Hi,

This is a good start, but the line number is fragile. pull.sh will overwrite the file with the latest esbuild_repo.bzl from upstream,  so a more robust script would need to inject the extra text in the correct place, eg in the line above register_default_toolchains(). If you don't want to do that, just printing the http_archive(...) lines so they can be copied and pasted in will be enough.

toolchain.bzl will also need to be updated to add the extra platform, and _default_toolchains will need to include the platform, as currently x86_64 is assumed.

Finally, please confirm you're happy to license your contributions under the 3 clause BSD license: https://github.com/ankitects/anki/blob/main/CONTRIBUTORS

**Comment by qubist-pixel-ux** [comment]
Python script now prints modification necessary for arm64 to stdout.

Changed toolchain.bzl and _default_toolchains to add arm64.

Pull request for CONTRIBUTORS file : https://github.com/ankitects/anki/pull/1205

**Comment by dae** [comment]
Thanks for that, I've updated the main repo to point at this updated version, so please try building from the latest main.

**Comment by qubist-pixel-ux** [comment]
Thanks to you too

**Pull request merged**
